import re

# LABEL CONSTANTS.
# Toplevel labels.
LABEL_ASSERTION = "ASSERTION"
LABEL_DOCUMENT = "DOCUMENT"
LABEL_FIXPOINT = "FIXPOINT"
LABEL_LTAC = "LTAC"
LABEL_NOTATION = "NOTATION"
LABEL_PROOF = "PROOF"
LABEL_REQUIRE_IMPORT = "REQUIRE_IMPORT"


# Toplevel subcomponent labels.
LABEL_ASSERTION_IDENT = "ASSERTION_IDENT"
LABEL_ASSERTION_KEYWORD = "ASSERTION_KEYWORD"
LABEL_ASSERTION_TERM = "ASSERTION_TERM"
LABEL_FORALL = "FORALL"
LABEL_TYPE = "TYPE"
LABEL_BINDER = "BINDER"

# Tactic command labels (alphabetically sorted).
LABEL_APPLY = "APPLY"
LABEL_ASSERT = "ASSERT"
LABEL_BULLET = "BULLET"
LABEL_CHECK = "CHECK"
LABEL_COMMENT = "COMMENT"
LABEL_COMPUTE = "COMPUTE"
LABEL_DESTRUCT = "DESTRUCT"
LABEL_ENOUGH = "ENOUGH"
LABEL_EXACT = "EXACT"
LABEL_EXISTS = "EXISTS"
LABEL_FOCUSED = "FOCUSED"
LABEL_FOLD = "FOLD"
LABEL_FOLD_UNFOLD = "FOLD_UNFOLD"
LABEL_INDUCTION = "INDUCTION"
LABEL_INTRO = "INTRO"
LABEL_INTROS = "INTROS"
LABEL_LEFT = "LEFT"
LABEL_RIGHT = "RIGHT"
LABEL_REFLEXIVITY = "REFLEXIVITY"
LABEL_RESTART = "RESTART"
LABEL_REWRITE = "REWRITE"
LABEL_SEARCH = "SEARCH"
LABEL_SPLIT = "SPLIT"
LABEL_SYMMETRY = "SYMMETRY"
LABEL_UNFOLD = "UNFOLD"

LABEL_GRP_TACTIC = [
    LABEL_APPLY,
    LABEL_ASSERT,
    LABEL_BULLET,
    LABEL_CHECK,
    LABEL_COMMENT,
    LABEL_COMPUTE,
    LABEL_DESTRUCT,
    LABEL_ENOUGH,
    LABEL_EXACT,
    LABEL_EXISTS,
    LABEL_FOCUSED,
    LABEL_FOLD,
    LABEL_FOLD_UNFOLD,
    LABEL_INDUCTION,
    LABEL_INTRO,
    LABEL_INTROS,
    LABEL_LEFT,
    LABEL_RIGHT,
    LABEL_REFLEXIVITY,
    LABEL_RESTART,
    LABEL_REWRITE,
    LABEL_SEARCH,
    LABEL_SPLIT,
    LABEL_SYMMETRY,
    LABEL_UNFOLD
]

# Tactic subcomponent labels.
LABEL_REWRITE_ARROW = "REWRITE_ARROW"
LABEL_TERM = "TERM"

# KEYWORD CONSTANTS.
# Toplevel keywords.
KW_ABORT = "Abort"
KW_ADMITTED = "Admitted"
KW_FIXPOINT = "Fixpoint"
KW_LTAC = "Ltac"
KW_NOTATION = "Notation"
KW_PROOF = "Proof"
KW_QED = "Qed"
KW_REQUIRE_IMPORT = "Require Import"

# Assertion and subcomponent keywords (alphabetically sorted).
KW_COROLLARY = "Corollary"
KW_DEFINITION = "Definition"
KW_EXAMPLE = "Example"
KW_FACT = "Fact"
KW_FORALL = "forall"
KW_LEMMA = "Lemma"
KW_PROPERTY = "Property"
KW_PROPOSITION = "Proposition"
KW_REMARK = "Remark"
KW_THEOREM = "Theorem"

# Tactic command keywords (alphabetically sorted).
KW_APPLY = "apply"
KW_ASSERT = "assert"
KW_CHECK = "Check"
KW_COMPUTE = "Compute"
KW_DESTRUCT = "destruct"
KW_ENOUGH = "enough"
KW_EXACT = "exact"
KW_EXISTS = "exists"
KW_FOLD = "fold"
KW_FOLD_UNFOLD = "fold_unfold_tactic"
KW_INDUCTION = "induction"
KW_INTRO = "intro"
KW_INTROS = "intros"
KW_LEFT = "left"
KW_RIGHT = "right"
KW_REFLEXIVITY = "reflexivity"
KW_RESTART = "Restart"
KW_REWRITE = "rewrite"
KW_SEARCH = "Search"
KW_SPLIT = "split"
KW_SYMMETRY = "symmetry"
KW_UNFOLD = "unfold"

# REGULAR EXPRESSION CONSTANTS (need to be included in keyword groups, so defined first).
REGEXP_BULLET = r"([\+\-\*]+\s*)"
REGEXP_COMMENT = r"(\s*\(\*.+?\*\)\s*)"
# Can't do nested focus unless we write a get_next_focused method.
REGEXP_FOCUSED = r"\s*\{\s*(.+?)\s*\}\s*"


# KEYWORD GROUPS.
KW_GRP_TACTIC = [
    KW_APPLY,
    KW_ASSERT,
    KW_CHECK,
    KW_COMPUTE,
    KW_DESTRUCT,
    KW_ENOUGH,
    KW_EXACT,
    KW_EXISTS,
    KW_FOLD,
    KW_FOLD_UNFOLD,
    KW_INDUCTION,
    KW_INTRO,
    KW_INTROS,
    KW_LEFT,
    KW_RIGHT,
    KW_REFLEXIVITY,
    KW_RESTART,
    KW_REWRITE,
    KW_SEARCH,
    KW_SPLIT,
    KW_SYMMETRY,
    KW_UNFOLD,
    REGEXP_COMMENT,
    REGEXP_FOCUSED
]


KW_GRP_ASSERTION = [
    KW_COROLLARY,
    KW_DEFINITION,
    KW_EXAMPLE,
    KW_FACT,
    KW_LEMMA,
    KW_PROPERTY,
    KW_PROPOSITION,
    KW_REMARK,
    KW_THEOREM,
]

KW_GRP_DOCUMENT = [
    KW_CHECK,
    KW_COMPUTE,
    KW_FIXPOINT,
    KW_LTAC,
    KW_NOTATION,
    KW_PROOF,
    KW_REQUIRE_IMPORT,
    KW_SEARCH,
    REGEXP_COMMENT,
] + KW_GRP_ASSERTION

# REGULAR EXPRESSION CONSTANTS.


def regx_non_capture_alt(grp):
    return f"(?:{'|'.join(grp)})"


REGEXP_ASSERTION = regx_non_capture_alt(KW_GRP_ASSERTION)
REGEXP_DOCUMENT = regx_non_capture_alt(KW_GRP_DOCUMENT)
REGEXP_TACTIC_END = r"[\.;]"
REGEXP_TACTIC = regx_non_capture_alt(KW_GRP_TACTIC)
REGEXP_TACTIC_LOOKAHEAD = f"(?=(?:{REGEXP_BULLET})?{REGEXP_TACTIC}|$)"
REGEXP_OR_AND_INTROPATTERN = r"(?:\[[^\.]+?\]|\S+?)"
REGEXP_IN_OCCURRENCE = r"(?:\sin\s\S+?)?"
REGEXP_AT_OCCURRENCE = r"(?:\sat(?:\s\d)+?)?"
REGEXP_AS_INTROPATTERN = fr"(?:\s?as\s?{REGEXP_OR_AND_INTROPATTERN})?"
REGEXP_USING_TERM = fr"(?:\susing\s\S+?)?"

REGEXP_DOC_LOOKAHEAD = f"(?=(?:{REGEXP_BULLET})?{REGEXP_TACTIC}|{REGEXP_DOCUMENT}|$)"
