# LABELS
LABEL_DOCUMENT = "DOCUMENT"
LABEL_PROOF = "PROOF"
LABEL_ASSERTION = "ASSERTION"
LABEL_INTRO = "INTRO"
LABEL_EXACT = "EXACT"
LABEL_TERM = "TERM"
LABEL_TERM_WITH_ARGS = "TERM_WITH_ARGS"
LABEL_IDENT = "IDENT"
LABEL_ARG = "ARG"
# LABEL_REWRITE = "REWRITE"

# KEYWORDS
KW_PROOF = "Proof"
KW_QED = "Qed"
KW_LEMMA = "Lemma"
KW_THEOREM = "Theorem"
KW_REMARK = "Remark"
KW_FACT = "Fact"
KW_COROLLARY = "Corollary"
KW_PROPERTY = "Property"
KW_PROPOSITION = "Proposition"
KW_DEFINITION = "Definition"
KW_EXAMPLE = "Example"

ASSERTION_KEYWORDS = (
    KW_THEOREM,
    KW_LEMMA,
    KW_REMARK,
    KW_FACT,
    KW_COROLLARY,
    KW_PROPERTY,
    KW_PROPOSITION,
    KW_DEFINITION,
    KW_EXAMPLE
)
