LABEL_DOCUMENT = "DOCUMENT"
LABEL_PROOF = "PROOF"
LABEL_ASSERTION = "ASSERTION"
# LABEL_SENTENCE = "SENTENCE"
# LABEL_TACTIC_INVOCATION = "TACTIC_INVOCATION"

KW_PROOF = "Proof"
KW_QED = "Qed"

KW_THEOREM = "Theorem"
KW_LEMMA = "Lemma"
KW_REMARK = "Remark"
KW_FACT = "Fact"
KW_COROLLARY = "Corollary"
KW_PROPERTY = "Property"
KW_PROPOSITION = "Proposition"
KW_DEFINITION = "Definition"
KW_EXAMPLE = "Example"

ASSERTION_KEYWORDS = (
    KW_THEOREM,
    KW_LEMMA,
    KW_REMARK,
    KW_FACT,
    KW_COROLLARY,
    KW_PROPERTY,
    KW_PROPOSITION,
    KW_DEFINITION,
    KW_EXAMPLE
)

KW_EXACT = "exact"
KW_REWRITE = "rewrite"
TACTIC_KEYWORDS = (
    KW_EXACT,
    KW_REWRITE
)

PATTERN_PROOF = r"Proof\..+?Qed\."
PATTERN_ASSERTION = r"Lemma [^\.]+?\."
PATTERNS = {
    LABEL_DOCUMENT: None,
    LABEL_PROOF: PATTERN_PROOF,
    LABEL_ASSERTION: PATTERN_ASSERTION
}

EMPTY = "EMPTY"
